kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deployment
  labels:
    app: asset-tracker-fe
    namespace: asset-tracker-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: asset-tracker-fe
  template:
    metadata:
      labels:
        app: asset-tracker-fe
    spec:
      containers:
      - name: asset-tracker-frontend
        image: pawarvaishnavi/asset-tracker-frontend:multistage
        ports:
        - containerPort: 5173

