kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: asset-tracker-ns

spec:
  selector:
    app: asset-tracker-be

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000  # container port


