kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: asset-tracker-ns
spec:
  clusterIP: None
  selector:
    app: asset-tracker-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432  # container port